title: "Enthusiastic"
description: >- # this means to ignore newlines until "baseurl:"
  ガジェット好き（？）の日誌、Enthusiasticです。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://diawadenta.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
plugins:
  - jekyll-feed
lang: ja-jp
markdown: kramdown
encoding: "utf-8"
